using UnityEngine;
using System.Collections;

public class GameOverScript : MonoBehaviour {

	public Texture2D go;

	private int playerNumber;

	public GameObject gdb;

	private int totalScore;

	public float originalWidth = 800.0f; 
	public float originalHeight = 480.0f; 
	Vector3 scale; 


	// Use this for initialization
	void Start () {

		scale.x = Screen.width/originalWidth;  
		scale.y = Screen.height/originalHeight; 
		scale.z = 1; 

		gdb = GameObject.Find ("GlobalDataBase");
	
	}
	
	// Update is called once per frame
	void Update () {

		playerNumber = GameObject.FindGameObjectsWithTag ("Player").Length;

		totalScore = gdb.GetComponent<GDB> ().enemyScore;
	
	}


	void OnGUI () {



		if (playerNumber == 0) {

			GUI.DrawTexture (new Rect (Screen.width / 2 - 200, 300, 400, 200), go);

			GUI.matrix = Matrix4x4.TRS (Vector3.zero, Quaternion.identity, scale);
			///rus
			if (MenuScript.lang == 1) {
				if (GUI.Button (new Rect (300, 100, 200, 50), "Меню уровней")) {
					GDB.globalScore = GDB.globalScore + totalScore;
					PlayerPrefs.SetInt ("activity", GDB.activity);
					PlayerPrefs.SetFloat ("xp", GDB.xp);
					PlayerPrefs.SetInt ("lev", GDB.levXp);
					PlayerPrefs.SetInt ("score", GDB.globalScore);
					PlayerPrefs.SetInt ("ruby", GDB.redMoney);
					PlayerPrefs.SetInt ("coin", GDB.coins);
					PlayerPrefs.SetInt ("level", GDB.unlockLeavel);
					PlayerPrefs.SetInt ("saphire", GDB.blueMoney);
					PlayerPrefs.SetInt ("emerald", GDB.greenMoney);
					PlayerPrefs.SetInt ("damage", MenuUpgrade.damageU);
					PlayerPrefs.SetInt ("health", MenuUpgrade.healthU);
					PlayerPrefs.SetInt ("speed", MenuUpgrade.speedU);
					PlayerPrefs.SetInt ("armor", MenuUpgrade.armorU);
					PlayerPrefs.SetInt ("char2", PlayerMenu.unlock_id_2);
					PlayerPrefs.SetInt ("char3", PlayerMenu.unlock_id_3);
					PlayerPrefs.SetInt ("char4", PlayerMenu.unlock_id_4);
					PlayerPrefs.SetInt ("char5", PlayerMenu.unlock_id_5);
					PlayerPrefs.SetInt ("char6", PlayerMenu.unlock_id_6);
					PlayerPrefs.SetInt ("char7", PlayerMenu.unlock_id_7);
					PlayerPrefs.SetInt ("char8", PlayerMenu.unlock_id_8);
					PlayerPrefs.SetInt ("char9", PlayerMenu.unlock_id_9);
					PlayerPrefs.SetInt ("char10", PlayerMenu.unlock_id_10);
					PlayerPrefs.SetInt ("char11", PlayerMenu.unlock_id_11);
					PlayerPrefs.SetInt ("char12", PlayerMenu.unlock_id_12);
					PlayerPrefs.SetInt ("char13", PlayerMenu.unlock_id_13);
					PlayerPrefs.SetInt ("char14", PlayerMenu.unlock_id_14);
					PlayerPrefs.SetInt ("char15", PlayerMenu.unlock_id_15);
					PlayerPrefs.SetInt ("char16", PlayerMenu.unlock_id_16);
					PlayerPrefs.SetInt ("char17", PlayerMenu.unlock_id_17);
					PlayerPrefs.SetInt ("char18", PlayerMenu.unlock_id_18);
					PlayerPrefs.SetInt ("char19", PlayerMenu.unlock_id_19);
					PlayerPrefs.SetInt ("char20", PlayerMenu.unlock_id_20);
					PlayerPrefs.SetInt ("char21", PlayerMenu.unlock_id_21);
					PlayerPrefs.SetInt ("char22", PlayerMenu.unlock_id_22);
					PlayerPrefs.SetInt ("char23", PlayerMenu.unlock_id_23);
					PlayerPrefs.SetInt ("char24", PlayerMenu.unlock_id_24);
					PlayerPrefs.SetInt ("char25", PlayerMenu.unlock_id_25);
					PlayerPrefs.SetInt ("char26", PlayerMenu.unlock_id_26);
					PlayerPrefs.SetInt ("char27", PlayerMenu.unlock_id_27);
					PlayerPrefs.SetInt ("char28", PlayerMenu.unlock_id_28);
					PlayerPrefs.SetInt ("char29", PlayerMenu.unlock_id_29);
					PlayerPrefs.SetInt ("char30", PlayerMenu.unlock_id_30);
					PlayerPrefs.SetInt ("char31", PlayerMenu.unlock_id_31);
					PlayerPrefs.SetInt ("char32", PlayerMenu.unlock_id_32);
					PlayerPrefs.SetInt ("char33", PlayerMenu.unlock_id_33);
					PlayerPrefs.SetInt ("char34", PlayerMenu.unlock_id_34);
					PlayerPrefs.SetInt ("char35", PlayerMenu.unlock_id_35);
					PlayerPrefs.SetInt ("char36", PlayerMenu.unlock_id_36);
					PlayerPrefs.SetInt ("char37", PlayerMenu.unlock_id_37);
					PlayerPrefs.SetInt ("char38", PlayerMenu.unlock_id_38);
					PlayerPrefs.SetInt ("char39", PlayerMenu.unlock_id_39);
					PlayerPrefs.SetInt ("char40", PlayerMenu.unlock_id_40);
					PlayerPrefs.SetInt ("char41", PlayerMenu.unlock_id_41);
					PlayerPrefs.SetInt ("char42", PlayerMenu.unlock_id_42);
					PlayerPrefs.SetInt ("char43", PlayerMenu.unlock_id_43);
					PlayerPrefs.SetInt ("char44", PlayerMenu.unlock_id_44);
					PlayerPrefs.SetInt ("char45", PlayerMenu.unlock_id_45);
					PlayerPrefs.SetInt ("char46", PlayerMenu.unlock_id_46);
					PlayerPrefs.SetInt ("char47", PlayerMenu.unlock_id_47);
					PlayerPrefs.SetInt ("char48", PlayerMenu.unlock_id_48);
					PlayerPrefs.SetInt ("char49", PlayerMenu.unlock_id_49);
					PlayerPrefs.SetInt ("char50", PlayerMenu.unlock_id_50);
					PlayerPrefs.SetInt ("char51", PlayerMenu.unlock_id_51);
					PlayerPrefs.SetInt ("char52", PlayerMenu.unlock_id_52);
					PlayerPrefs.SetInt ("char53", PlayerMenu.unlock_id_53);
					PlayerPrefs.SetInt ("char54", PlayerMenu.unlock_id_54);
					PlayerPrefs.SetInt ("char55", PlayerMenu.unlock_id_55);
					PlayerPrefs.SetInt ("char56", PlayerMenu.unlock_id_56);
					PlayerPrefs.SetInt ("char57", PlayerMenu.unlock_id_57);
					PlayerPrefs.SetInt ("char58", PlayerMenu.unlock_id_58);
					PlayerPrefs.SetInt ("char59", PlayerMenu.unlock_id_59);
					PlayerPrefs.SetInt ("char60", PlayerMenu.unlock_id_60);
					PlayerPrefs.SetInt ("char61", PlayerMenu.unlock_id_61);
					PlayerPrefs.SetInt ("char62", PlayerMenu.unlock_id_62);
					PlayerPrefs.SetInt ("char63", PlayerMenu.unlock_id_63);
					Application.LoadLevel ("LevelMenu");
				}

				if (GUI.Button (new Rect (300, 220, 200, 50), "Главное меню")) {
					GDB.globalScore = GDB.globalScore + totalScore;
					PlayerPrefs.SetInt ("activity", GDB.activity);
					PlayerPrefs.SetFloat ("xp", GDB.xp);
					PlayerPrefs.SetInt ("lev", GDB.levXp);
					PlayerPrefs.SetInt ("score", GDB.globalScore);
					PlayerPrefs.SetInt ("ruby", GDB.redMoney);
					PlayerPrefs.SetInt ("coin", GDB.coins);
					PlayerPrefs.SetInt ("level", GDB.unlockLeavel);
					PlayerPrefs.SetInt ("saphire", GDB.blueMoney);
					PlayerPrefs.SetInt ("emerald", GDB.greenMoney);
					PlayerPrefs.SetInt ("damage", MenuUpgrade.damageU);
					PlayerPrefs.SetInt ("health", MenuUpgrade.healthU);
					PlayerPrefs.SetInt ("speed", MenuUpgrade.speedU);
					PlayerPrefs.SetInt ("armor", MenuUpgrade.armorU);
					PlayerPrefs.SetInt ("char2", PlayerMenu.unlock_id_2);
					PlayerPrefs.SetInt ("char3", PlayerMenu.unlock_id_3);
					PlayerPrefs.SetInt ("char4", PlayerMenu.unlock_id_4);
					PlayerPrefs.SetInt ("char5", PlayerMenu.unlock_id_5);
					PlayerPrefs.SetInt ("char6", PlayerMenu.unlock_id_6);
					PlayerPrefs.SetInt ("char7", PlayerMenu.unlock_id_7);
					PlayerPrefs.SetInt ("char8", PlayerMenu.unlock_id_8);
					PlayerPrefs.SetInt ("char9", PlayerMenu.unlock_id_9);
					PlayerPrefs.SetInt ("char10", PlayerMenu.unlock_id_10);
					PlayerPrefs.SetInt ("char11", PlayerMenu.unlock_id_11);
					PlayerPrefs.SetInt ("char12", PlayerMenu.unlock_id_12);
					PlayerPrefs.SetInt ("char13", PlayerMenu.unlock_id_13);
					PlayerPrefs.SetInt ("char14", PlayerMenu.unlock_id_14);
					PlayerPrefs.SetInt ("char15", PlayerMenu.unlock_id_15);
					PlayerPrefs.SetInt ("char16", PlayerMenu.unlock_id_16);
					PlayerPrefs.SetInt ("char17", PlayerMenu.unlock_id_17);
					PlayerPrefs.SetInt ("char18", PlayerMenu.unlock_id_18);
					PlayerPrefs.SetInt ("char19", PlayerMenu.unlock_id_19);
					PlayerPrefs.SetInt ("char20", PlayerMenu.unlock_id_20);
					PlayerPrefs.SetInt ("char21", PlayerMenu.unlock_id_21);
					PlayerPrefs.SetInt ("char22", PlayerMenu.unlock_id_22);
					PlayerPrefs.SetInt ("char23", PlayerMenu.unlock_id_23);
					PlayerPrefs.SetInt ("char24", PlayerMenu.unlock_id_24);
					PlayerPrefs.SetInt ("char25", PlayerMenu.unlock_id_25);
					PlayerPrefs.SetInt ("char26", PlayerMenu.unlock_id_26);
					PlayerPrefs.SetInt ("char27", PlayerMenu.unlock_id_27);
					PlayerPrefs.SetInt ("char28", PlayerMenu.unlock_id_28);
					PlayerPrefs.SetInt ("char29", PlayerMenu.unlock_id_29);
					PlayerPrefs.SetInt ("char30", PlayerMenu.unlock_id_30);
					PlayerPrefs.SetInt ("char31", PlayerMenu.unlock_id_31);
					PlayerPrefs.SetInt ("char32", PlayerMenu.unlock_id_32);
					PlayerPrefs.SetInt ("char33", PlayerMenu.unlock_id_33);
					PlayerPrefs.SetInt ("char34", PlayerMenu.unlock_id_34);
					PlayerPrefs.SetInt ("char35", PlayerMenu.unlock_id_35);
					PlayerPrefs.SetInt ("char36", PlayerMenu.unlock_id_36);
					PlayerPrefs.SetInt ("char37", PlayerMenu.unlock_id_37);
					PlayerPrefs.SetInt ("char38", PlayerMenu.unlock_id_38);
					PlayerPrefs.SetInt ("char39", PlayerMenu.unlock_id_39);
					PlayerPrefs.SetInt ("char40", PlayerMenu.unlock_id_40);
					PlayerPrefs.SetInt ("char41", PlayerMenu.unlock_id_41);
					PlayerPrefs.SetInt ("char42", PlayerMenu.unlock_id_42);
					PlayerPrefs.SetInt ("char43", PlayerMenu.unlock_id_43);
					PlayerPrefs.SetInt ("char44", PlayerMenu.unlock_id_44);
					PlayerPrefs.SetInt ("char45", PlayerMenu.unlock_id_45);
					PlayerPrefs.SetInt ("char46", PlayerMenu.unlock_id_46);
					PlayerPrefs.SetInt ("char47", PlayerMenu.unlock_id_47);
					PlayerPrefs.SetInt ("char48", PlayerMenu.unlock_id_48);
					PlayerPrefs.SetInt ("char49", PlayerMenu.unlock_id_49);
					PlayerPrefs.SetInt ("char50", PlayerMenu.unlock_id_50);
					PlayerPrefs.SetInt ("char51", PlayerMenu.unlock_id_51);
					PlayerPrefs.SetInt ("char52", PlayerMenu.unlock_id_52);
					PlayerPrefs.SetInt ("char53", PlayerMenu.unlock_id_53);
					PlayerPrefs.SetInt ("char54", PlayerMenu.unlock_id_54);
					PlayerPrefs.SetInt ("char55", PlayerMenu.unlock_id_55);
					PlayerPrefs.SetInt ("char56", PlayerMenu.unlock_id_56);
					PlayerPrefs.SetInt ("char57", PlayerMenu.unlock_id_57);
					PlayerPrefs.SetInt ("char58", PlayerMenu.unlock_id_58);
					PlayerPrefs.SetInt ("char59", PlayerMenu.unlock_id_59);
					PlayerPrefs.SetInt ("char60", PlayerMenu.unlock_id_60);
					PlayerPrefs.SetInt ("char61", PlayerMenu.unlock_id_61);
					PlayerPrefs.SetInt ("char62", PlayerMenu.unlock_id_62);
					PlayerPrefs.SetInt ("char63", PlayerMenu.unlock_id_63);
					Application.LoadLevel ("Menu");
				}

				if (GUI.Button (new Rect (300, 160, 200, 50), "Меню смайлов")) {
					GDB.globalScore = GDB.globalScore + totalScore;
					PlayerPrefs.SetInt ("activity", GDB.activity);
					PlayerPrefs.SetFloat ("xp", GDB.xp);
					PlayerPrefs.SetInt ("lev", GDB.levXp);
					PlayerPrefs.SetInt ("score", GDB.globalScore);
					PlayerPrefs.SetInt ("ruby", GDB.redMoney);
					PlayerPrefs.SetInt ("coin", GDB.coins);
					PlayerPrefs.SetInt ("level", GDB.unlockLeavel);
					PlayerPrefs.SetInt ("saphire", GDB.blueMoney);
					PlayerPrefs.SetInt ("emerald", GDB.greenMoney);
					PlayerPrefs.SetInt ("damage", MenuUpgrade.damageU);
					PlayerPrefs.SetInt ("health", MenuUpgrade.healthU);
					PlayerPrefs.SetInt ("speed", MenuUpgrade.speedU);
					PlayerPrefs.SetInt ("armor", MenuUpgrade.armorU);
					PlayerPrefs.SetInt ("char2", PlayerMenu.unlock_id_2);
					PlayerPrefs.SetInt ("char3", PlayerMenu.unlock_id_3);
					PlayerPrefs.SetInt ("char4", PlayerMenu.unlock_id_4);
					PlayerPrefs.SetInt ("char5", PlayerMenu.unlock_id_5);
					PlayerPrefs.SetInt ("char6", PlayerMenu.unlock_id_6);
					PlayerPrefs.SetInt ("char7", PlayerMenu.unlock_id_7);
					PlayerPrefs.SetInt ("char8", PlayerMenu.unlock_id_8);
					PlayerPrefs.SetInt ("char9", PlayerMenu.unlock_id_9);
					PlayerPrefs.SetInt ("char10", PlayerMenu.unlock_id_10);
					PlayerPrefs.SetInt ("char11", PlayerMenu.unlock_id_11);
					PlayerPrefs.SetInt ("char12", PlayerMenu.unlock_id_12);
					PlayerPrefs.SetInt ("char13", PlayerMenu.unlock_id_13);
					PlayerPrefs.SetInt ("char14", PlayerMenu.unlock_id_14);
					PlayerPrefs.SetInt ("char15", PlayerMenu.unlock_id_15);
					PlayerPrefs.SetInt ("char16", PlayerMenu.unlock_id_16);
					PlayerPrefs.SetInt ("char17", PlayerMenu.unlock_id_17);
					PlayerPrefs.SetInt ("char18", PlayerMenu.unlock_id_18);
					PlayerPrefs.SetInt ("char19", PlayerMenu.unlock_id_19);
					PlayerPrefs.SetInt ("char20", PlayerMenu.unlock_id_20);
					PlayerPrefs.SetInt ("char21", PlayerMenu.unlock_id_21);
					PlayerPrefs.SetInt ("char22", PlayerMenu.unlock_id_22);
					PlayerPrefs.SetInt ("char23", PlayerMenu.unlock_id_23);
					PlayerPrefs.SetInt ("char24", PlayerMenu.unlock_id_24);
					PlayerPrefs.SetInt ("char25", PlayerMenu.unlock_id_25);
					PlayerPrefs.SetInt ("char26", PlayerMenu.unlock_id_26);
					PlayerPrefs.SetInt ("char27", PlayerMenu.unlock_id_27);
					PlayerPrefs.SetInt ("char28", PlayerMenu.unlock_id_28);
					PlayerPrefs.SetInt ("char29", PlayerMenu.unlock_id_29);
					PlayerPrefs.SetInt ("char30", PlayerMenu.unlock_id_30);
					PlayerPrefs.SetInt ("char31", PlayerMenu.unlock_id_31);
					PlayerPrefs.SetInt ("char32", PlayerMenu.unlock_id_32);
					PlayerPrefs.SetInt ("char33", PlayerMenu.unlock_id_33);
					PlayerPrefs.SetInt ("char34", PlayerMenu.unlock_id_34);
					PlayerPrefs.SetInt ("char35", PlayerMenu.unlock_id_35);
					PlayerPrefs.SetInt ("char36", PlayerMenu.unlock_id_36);
					PlayerPrefs.SetInt ("char37", PlayerMenu.unlock_id_37);
					PlayerPrefs.SetInt ("char38", PlayerMenu.unlock_id_38);
					PlayerPrefs.SetInt ("char39", PlayerMenu.unlock_id_39);
					PlayerPrefs.SetInt ("char40", PlayerMenu.unlock_id_40);
					PlayerPrefs.SetInt ("char41", PlayerMenu.unlock_id_41);
					PlayerPrefs.SetInt ("char42", PlayerMenu.unlock_id_42);
					PlayerPrefs.SetInt ("char43", PlayerMenu.unlock_id_43);
					PlayerPrefs.SetInt ("char44", PlayerMenu.unlock_id_44);
					PlayerPrefs.SetInt ("char45", PlayerMenu.unlock_id_45);
					PlayerPrefs.SetInt ("char46", PlayerMenu.unlock_id_46);
					PlayerPrefs.SetInt ("char47", PlayerMenu.unlock_id_47);
					PlayerPrefs.SetInt ("char48", PlayerMenu.unlock_id_48);
					PlayerPrefs.SetInt ("char49", PlayerMenu.unlock_id_49);
					PlayerPrefs.SetInt ("char50", PlayerMenu.unlock_id_50);
					PlayerPrefs.SetInt ("char51", PlayerMenu.unlock_id_51);
					PlayerPrefs.SetInt ("char52", PlayerMenu.unlock_id_52);
					PlayerPrefs.SetInt ("char53", PlayerMenu.unlock_id_53);
					PlayerPrefs.SetInt ("char54", PlayerMenu.unlock_id_54);
					PlayerPrefs.SetInt ("char55", PlayerMenu.unlock_id_55);
					PlayerPrefs.SetInt ("char56", PlayerMenu.unlock_id_56);
					PlayerPrefs.SetInt ("char57", PlayerMenu.unlock_id_57);
					PlayerPrefs.SetInt ("char58", PlayerMenu.unlock_id_58);
					PlayerPrefs.SetInt ("char59", PlayerMenu.unlock_id_59);
					PlayerPrefs.SetInt ("char60", PlayerMenu.unlock_id_60);
					PlayerPrefs.SetInt ("char61", PlayerMenu.unlock_id_61);
					PlayerPrefs.SetInt ("char62", PlayerMenu.unlock_id_62);
					PlayerPrefs.SetInt ("char63", PlayerMenu.unlock_id_63);
					Application.LoadLevel ("PlayerMenu");
				}
			}
			///eng
			if (MenuScript.lang == 2) {
				if (GUI.Button (new Rect (300, 100, 200, 50), "Level Menu")) {
					GDB.globalScore = GDB.globalScore + totalScore;
					PlayerPrefs.SetInt ("activity", GDB.activity);
					PlayerPrefs.SetFloat ("xp", GDB.xp);
					PlayerPrefs.SetInt ("lev", GDB.levXp);
					PlayerPrefs.SetInt ("score", GDB.globalScore);
					PlayerPrefs.SetInt ("ruby", GDB.redMoney);
					PlayerPrefs.SetInt ("coin", GDB.coins);
					PlayerPrefs.SetInt ("level", GDB.unlockLeavel);
					PlayerPrefs.SetInt ("saphire", GDB.blueMoney);
					PlayerPrefs.SetInt ("emerald", GDB.greenMoney);
					PlayerPrefs.SetInt ("damage", MenuUpgrade.damageU);
					PlayerPrefs.SetInt ("health", MenuUpgrade.healthU);
					PlayerPrefs.SetInt ("speed", MenuUpgrade.speedU);
					PlayerPrefs.SetInt ("armor", MenuUpgrade.armorU);
					PlayerPrefs.SetInt ("char2", PlayerMenu.unlock_id_2);
					PlayerPrefs.SetInt ("char3", PlayerMenu.unlock_id_3);
					PlayerPrefs.SetInt ("char4", PlayerMenu.unlock_id_4);
					PlayerPrefs.SetInt ("char5", PlayerMenu.unlock_id_5);
					PlayerPrefs.SetInt ("char6", PlayerMenu.unlock_id_6);
					PlayerPrefs.SetInt ("char7", PlayerMenu.unlock_id_7);
					PlayerPrefs.SetInt ("char8", PlayerMenu.unlock_id_8);
					PlayerPrefs.SetInt ("char9", PlayerMenu.unlock_id_9);
					PlayerPrefs.SetInt ("char10", PlayerMenu.unlock_id_10);
					PlayerPrefs.SetInt ("char11", PlayerMenu.unlock_id_11);
					PlayerPrefs.SetInt ("char12", PlayerMenu.unlock_id_12);
					PlayerPrefs.SetInt ("char13", PlayerMenu.unlock_id_13);
					PlayerPrefs.SetInt ("char14", PlayerMenu.unlock_id_14);
					PlayerPrefs.SetInt ("char15", PlayerMenu.unlock_id_15);
					PlayerPrefs.SetInt ("char16", PlayerMenu.unlock_id_16);
					PlayerPrefs.SetInt ("char17", PlayerMenu.unlock_id_17);
					PlayerPrefs.SetInt ("char18", PlayerMenu.unlock_id_18);
					PlayerPrefs.SetInt ("char19", PlayerMenu.unlock_id_19);
					PlayerPrefs.SetInt ("char20", PlayerMenu.unlock_id_20);
					PlayerPrefs.SetInt ("char21", PlayerMenu.unlock_id_21);
					PlayerPrefs.SetInt ("char22", PlayerMenu.unlock_id_22);
					PlayerPrefs.SetInt ("char23", PlayerMenu.unlock_id_23);
					PlayerPrefs.SetInt ("char24", PlayerMenu.unlock_id_24);
					PlayerPrefs.SetInt ("char25", PlayerMenu.unlock_id_25);
					PlayerPrefs.SetInt ("char26", PlayerMenu.unlock_id_26);
					PlayerPrefs.SetInt ("char27", PlayerMenu.unlock_id_27);
					PlayerPrefs.SetInt ("char28", PlayerMenu.unlock_id_28);
					PlayerPrefs.SetInt ("char29", PlayerMenu.unlock_id_29);
					PlayerPrefs.SetInt ("char30", PlayerMenu.unlock_id_30);
					PlayerPrefs.SetInt ("char31", PlayerMenu.unlock_id_31);
					PlayerPrefs.SetInt ("char32", PlayerMenu.unlock_id_32);
					PlayerPrefs.SetInt ("char33", PlayerMenu.unlock_id_33);
					PlayerPrefs.SetInt ("char34", PlayerMenu.unlock_id_34);
					PlayerPrefs.SetInt ("char35", PlayerMenu.unlock_id_35);
					PlayerPrefs.SetInt ("char36", PlayerMenu.unlock_id_36);
					PlayerPrefs.SetInt ("char37", PlayerMenu.unlock_id_37);
					PlayerPrefs.SetInt ("char38", PlayerMenu.unlock_id_38);
					PlayerPrefs.SetInt ("char39", PlayerMenu.unlock_id_39);
					PlayerPrefs.SetInt ("char40", PlayerMenu.unlock_id_40);
					PlayerPrefs.SetInt ("char41", PlayerMenu.unlock_id_41);
					PlayerPrefs.SetInt ("char42", PlayerMenu.unlock_id_42);
					PlayerPrefs.SetInt ("char43", PlayerMenu.unlock_id_43);
					PlayerPrefs.SetInt ("char44", PlayerMenu.unlock_id_44);
					PlayerPrefs.SetInt ("char45", PlayerMenu.unlock_id_45);
					PlayerPrefs.SetInt ("char46", PlayerMenu.unlock_id_46);
					PlayerPrefs.SetInt ("char47", PlayerMenu.unlock_id_47);
					PlayerPrefs.SetInt ("char48", PlayerMenu.unlock_id_48);
					PlayerPrefs.SetInt ("char49", PlayerMenu.unlock_id_49);
					PlayerPrefs.SetInt ("char50", PlayerMenu.unlock_id_50);
					PlayerPrefs.SetInt ("char51", PlayerMenu.unlock_id_51);
					PlayerPrefs.SetInt ("char52", PlayerMenu.unlock_id_52);
					PlayerPrefs.SetInt ("char53", PlayerMenu.unlock_id_53);
					PlayerPrefs.SetInt ("char54", PlayerMenu.unlock_id_54);
					PlayerPrefs.SetInt ("char55", PlayerMenu.unlock_id_55);
					PlayerPrefs.SetInt ("char56", PlayerMenu.unlock_id_56);
					PlayerPrefs.SetInt ("char57", PlayerMenu.unlock_id_57);
					PlayerPrefs.SetInt ("char58", PlayerMenu.unlock_id_58);
					PlayerPrefs.SetInt ("char59", PlayerMenu.unlock_id_59);
					PlayerPrefs.SetInt ("char60", PlayerMenu.unlock_id_60);
					PlayerPrefs.SetInt ("char61", PlayerMenu.unlock_id_61);
					PlayerPrefs.SetInt ("char62", PlayerMenu.unlock_id_62);
					PlayerPrefs.SetInt ("char63", PlayerMenu.unlock_id_63);
					Application.LoadLevel ("LevelMenu");
				}
				
				if (GUI.Button (new Rect (300, 220, 200, 50), "Main Menu")) {
					GDB.globalScore = GDB.globalScore + totalScore;
					PlayerPrefs.SetInt ("activity", GDB.activity);
					PlayerPrefs.SetFloat ("xp", GDB.xp);
					PlayerPrefs.SetInt ("lev", GDB.levXp);
					PlayerPrefs.SetInt ("score", GDB.globalScore);
					PlayerPrefs.SetInt ("ruby", GDB.redMoney);
					PlayerPrefs.SetInt ("coin", GDB.coins);
					PlayerPrefs.SetInt ("level", GDB.unlockLeavel);
					PlayerPrefs.SetInt ("saphire", GDB.blueMoney);
					PlayerPrefs.SetInt ("emerald", GDB.greenMoney);
					PlayerPrefs.SetInt ("damage", MenuUpgrade.damageU);
					PlayerPrefs.SetInt ("health", MenuUpgrade.healthU);
					PlayerPrefs.SetInt ("speed", MenuUpgrade.speedU);
					PlayerPrefs.SetInt ("armor", MenuUpgrade.armorU);
					PlayerPrefs.SetInt ("char2", PlayerMenu.unlock_id_2);
					PlayerPrefs.SetInt ("char3", PlayerMenu.unlock_id_3);
					PlayerPrefs.SetInt ("char4", PlayerMenu.unlock_id_4);
					PlayerPrefs.SetInt ("char5", PlayerMenu.unlock_id_5);
					PlayerPrefs.SetInt ("char6", PlayerMenu.unlock_id_6);
					PlayerPrefs.SetInt ("char7", PlayerMenu.unlock_id_7);
					PlayerPrefs.SetInt ("char8", PlayerMenu.unlock_id_8);
					PlayerPrefs.SetInt ("char9", PlayerMenu.unlock_id_9);
					PlayerPrefs.SetInt ("char10", PlayerMenu.unlock_id_10);
					PlayerPrefs.SetInt ("char11", PlayerMenu.unlock_id_11);
					PlayerPrefs.SetInt ("char12", PlayerMenu.unlock_id_12);
					PlayerPrefs.SetInt ("char13", PlayerMenu.unlock_id_13);
					PlayerPrefs.SetInt ("char14", PlayerMenu.unlock_id_14);
					PlayerPrefs.SetInt ("char15", PlayerMenu.unlock_id_15);
					PlayerPrefs.SetInt ("char16", PlayerMenu.unlock_id_16);
					PlayerPrefs.SetInt ("char17", PlayerMenu.unlock_id_17);
					PlayerPrefs.SetInt ("char18", PlayerMenu.unlock_id_18);
					PlayerPrefs.SetInt ("char19", PlayerMenu.unlock_id_19);
					PlayerPrefs.SetInt ("char20", PlayerMenu.unlock_id_20);
					PlayerPrefs.SetInt ("char21", PlayerMenu.unlock_id_21);
					PlayerPrefs.SetInt ("char22", PlayerMenu.unlock_id_22);
					PlayerPrefs.SetInt ("char23", PlayerMenu.unlock_id_23);
					PlayerPrefs.SetInt ("char24", PlayerMenu.unlock_id_24);
					PlayerPrefs.SetInt ("char25", PlayerMenu.unlock_id_25);
					PlayerPrefs.SetInt ("char26", PlayerMenu.unlock_id_26);
					PlayerPrefs.SetInt ("char27", PlayerMenu.unlock_id_27);
					PlayerPrefs.SetInt ("char28", PlayerMenu.unlock_id_28);
					PlayerPrefs.SetInt ("char29", PlayerMenu.unlock_id_29);
					PlayerPrefs.SetInt ("char30", PlayerMenu.unlock_id_30);
					PlayerPrefs.SetInt ("char31", PlayerMenu.unlock_id_31);
					PlayerPrefs.SetInt ("char32", PlayerMenu.unlock_id_32);
					PlayerPrefs.SetInt ("char33", PlayerMenu.unlock_id_33);
					PlayerPrefs.SetInt ("char34", PlayerMenu.unlock_id_34);
					PlayerPrefs.SetInt ("char35", PlayerMenu.unlock_id_35);
					PlayerPrefs.SetInt ("char36", PlayerMenu.unlock_id_36);
					PlayerPrefs.SetInt ("char37", PlayerMenu.unlock_id_37);
					PlayerPrefs.SetInt ("char38", PlayerMenu.unlock_id_38);
					PlayerPrefs.SetInt ("char39", PlayerMenu.unlock_id_39);
					PlayerPrefs.SetInt ("char40", PlayerMenu.unlock_id_40);
					PlayerPrefs.SetInt ("char41", PlayerMenu.unlock_id_41);
					PlayerPrefs.SetInt ("char42", PlayerMenu.unlock_id_42);
					PlayerPrefs.SetInt ("char43", PlayerMenu.unlock_id_43);
					PlayerPrefs.SetInt ("char44", PlayerMenu.unlock_id_44);
					PlayerPrefs.SetInt ("char45", PlayerMenu.unlock_id_45);
					PlayerPrefs.SetInt ("char46", PlayerMenu.unlock_id_46);
					PlayerPrefs.SetInt ("char47", PlayerMenu.unlock_id_47);
					PlayerPrefs.SetInt ("char48", PlayerMenu.unlock_id_48);
					PlayerPrefs.SetInt ("char49", PlayerMenu.unlock_id_49);
					PlayerPrefs.SetInt ("char50", PlayerMenu.unlock_id_50);
					PlayerPrefs.SetInt ("char51", PlayerMenu.unlock_id_51);
					PlayerPrefs.SetInt ("char52", PlayerMenu.unlock_id_52);
					PlayerPrefs.SetInt ("char53", PlayerMenu.unlock_id_53);
					PlayerPrefs.SetInt ("char54", PlayerMenu.unlock_id_54);
					PlayerPrefs.SetInt ("char55", PlayerMenu.unlock_id_55);
					PlayerPrefs.SetInt ("char56", PlayerMenu.unlock_id_56);
					PlayerPrefs.SetInt ("char57", PlayerMenu.unlock_id_57);
					PlayerPrefs.SetInt ("char58", PlayerMenu.unlock_id_58);
					PlayerPrefs.SetInt ("char59", PlayerMenu.unlock_id_59);
					PlayerPrefs.SetInt ("char60", PlayerMenu.unlock_id_60);
					PlayerPrefs.SetInt ("char61", PlayerMenu.unlock_id_61);
					PlayerPrefs.SetInt ("char62", PlayerMenu.unlock_id_62);
					PlayerPrefs.SetInt ("char63", PlayerMenu.unlock_id_63);
					Application.LoadLevel ("Menu");
				}
				
				if (GUI.Button (new Rect (300, 160, 200, 50), "Characters")) {
					GDB.globalScore = GDB.globalScore + totalScore;
					PlayerPrefs.SetInt ("activity", GDB.activity);
					PlayerPrefs.SetFloat ("xp", GDB.xp);
					PlayerPrefs.SetInt ("lev", GDB.levXp);
					PlayerPrefs.SetInt ("score", GDB.globalScore);
					PlayerPrefs.SetInt ("ruby", GDB.redMoney);
					PlayerPrefs.SetInt ("coin", GDB.coins);
					PlayerPrefs.SetInt ("level", GDB.unlockLeavel);
					PlayerPrefs.SetInt ("saphire", GDB.blueMoney);
					PlayerPrefs.SetInt ("emerald", GDB.greenMoney);
					PlayerPrefs.SetInt ("damage", MenuUpgrade.damageU);
					PlayerPrefs.SetInt ("health", MenuUpgrade.healthU);
					PlayerPrefs.SetInt ("speed", MenuUpgrade.speedU);
					PlayerPrefs.SetInt ("armor", MenuUpgrade.armorU);
					PlayerPrefs.SetInt ("char2", PlayerMenu.unlock_id_2);
					PlayerPrefs.SetInt ("char3", PlayerMenu.unlock_id_3);
					PlayerPrefs.SetInt ("char4", PlayerMenu.unlock_id_4);
					PlayerPrefs.SetInt ("char5", PlayerMenu.unlock_id_5);
					PlayerPrefs.SetInt ("char6", PlayerMenu.unlock_id_6);
					PlayerPrefs.SetInt ("char7", PlayerMenu.unlock_id_7);
					PlayerPrefs.SetInt ("char8", PlayerMenu.unlock_id_8);
					PlayerPrefs.SetInt ("char9", PlayerMenu.unlock_id_9);
					PlayerPrefs.SetInt ("char10", PlayerMenu.unlock_id_10);
					PlayerPrefs.SetInt ("char11", PlayerMenu.unlock_id_11);
					PlayerPrefs.SetInt ("char12", PlayerMenu.unlock_id_12);
					PlayerPrefs.SetInt ("char13", PlayerMenu.unlock_id_13);
					PlayerPrefs.SetInt ("char14", PlayerMenu.unlock_id_14);
					PlayerPrefs.SetInt ("char15", PlayerMenu.unlock_id_15);
					PlayerPrefs.SetInt ("char16", PlayerMenu.unlock_id_16);
					PlayerPrefs.SetInt ("char17", PlayerMenu.unlock_id_17);
					PlayerPrefs.SetInt ("char18", PlayerMenu.unlock_id_18);
					PlayerPrefs.SetInt ("char19", PlayerMenu.unlock_id_19);
					PlayerPrefs.SetInt ("char20", PlayerMenu.unlock_id_20);
					PlayerPrefs.SetInt ("char21", PlayerMenu.unlock_id_21);
					PlayerPrefs.SetInt ("char22", PlayerMenu.unlock_id_22);
					PlayerPrefs.SetInt ("char23", PlayerMenu.unlock_id_23);
					PlayerPrefs.SetInt ("char24", PlayerMenu.unlock_id_24);
					PlayerPrefs.SetInt ("char25", PlayerMenu.unlock_id_25);
					PlayerPrefs.SetInt ("char26", PlayerMenu.unlock_id_26);
					PlayerPrefs.SetInt ("char27", PlayerMenu.unlock_id_27);
					PlayerPrefs.SetInt ("char28", PlayerMenu.unlock_id_28);
					PlayerPrefs.SetInt ("char29", PlayerMenu.unlock_id_29);
					PlayerPrefs.SetInt ("char30", PlayerMenu.unlock_id_30);
					PlayerPrefs.SetInt ("char31", PlayerMenu.unlock_id_31);
					PlayerPrefs.SetInt ("char32", PlayerMenu.unlock_id_32);
					PlayerPrefs.SetInt ("char33", PlayerMenu.unlock_id_33);
					PlayerPrefs.SetInt ("char34", PlayerMenu.unlock_id_34);
					PlayerPrefs.SetInt ("char35", PlayerMenu.unlock_id_35);
					PlayerPrefs.SetInt ("char36", PlayerMenu.unlock_id_36);
					PlayerPrefs.SetInt ("char37", PlayerMenu.unlock_id_37);
					PlayerPrefs.SetInt ("char38", PlayerMenu.unlock_id_38);
					PlayerPrefs.SetInt ("char39", PlayerMenu.unlock_id_39);
					PlayerPrefs.SetInt ("char40", PlayerMenu.unlock_id_40);
					PlayerPrefs.SetInt ("char41", PlayerMenu.unlock_id_41);
					PlayerPrefs.SetInt ("char42", PlayerMenu.unlock_id_42);
					PlayerPrefs.SetInt ("char43", PlayerMenu.unlock_id_43);
					PlayerPrefs.SetInt ("char44", PlayerMenu.unlock_id_44);
					PlayerPrefs.SetInt ("char45", PlayerMenu.unlock_id_45);
					PlayerPrefs.SetInt ("char46", PlayerMenu.unlock_id_46);
					PlayerPrefs.SetInt ("char47", PlayerMenu.unlock_id_47);
					PlayerPrefs.SetInt ("char48", PlayerMenu.unlock_id_48);
					PlayerPrefs.SetInt ("char49", PlayerMenu.unlock_id_49);
					PlayerPrefs.SetInt ("char50", PlayerMenu.unlock_id_50);
					PlayerPrefs.SetInt ("char51", PlayerMenu.unlock_id_51);
					PlayerPrefs.SetInt ("char52", PlayerMenu.unlock_id_52);
					PlayerPrefs.SetInt ("char53", PlayerMenu.unlock_id_53);
					PlayerPrefs.SetInt ("char54", PlayerMenu.unlock_id_54);
					PlayerPrefs.SetInt ("char55", PlayerMenu.unlock_id_55);
					PlayerPrefs.SetInt ("char56", PlayerMenu.unlock_id_56);
					PlayerPrefs.SetInt ("char57", PlayerMenu.unlock_id_57);
					PlayerPrefs.SetInt ("char58", PlayerMenu.unlock_id_58);
					PlayerPrefs.SetInt ("char59", PlayerMenu.unlock_id_59);
					PlayerPrefs.SetInt ("char60", PlayerMenu.unlock_id_60);
					PlayerPrefs.SetInt ("char61", PlayerMenu.unlock_id_61);
					PlayerPrefs.SetInt ("char62", PlayerMenu.unlock_id_62);
					PlayerPrefs.SetInt ("char63", PlayerMenu.unlock_id_63);
					Application.LoadLevel ("PlayerMenu");
				}
			}
			///chi
			if (MenuScript.lang == 3) {
				if (GUI.Button (new Rect (300, 100, 200, 50), "该级别的菜单")) {
					GDB.globalScore = GDB.globalScore + totalScore;
					PlayerPrefs.SetInt ("activity", GDB.activity);
					PlayerPrefs.SetFloat ("xp", GDB.xp);
					PlayerPrefs.SetInt ("lev", GDB.levXp);
					PlayerPrefs.SetInt ("score", GDB.globalScore);
					PlayerPrefs.SetInt ("ruby", GDB.redMoney);
					PlayerPrefs.SetInt ("coin", GDB.coins);
					PlayerPrefs.SetInt ("level", GDB.unlockLeavel);
					PlayerPrefs.SetInt ("saphire", GDB.blueMoney);
					PlayerPrefs.SetInt ("emerald", GDB.greenMoney);
					PlayerPrefs.SetInt ("damage", MenuUpgrade.damageU);
					PlayerPrefs.SetInt ("health", MenuUpgrade.healthU);
					PlayerPrefs.SetInt ("speed", MenuUpgrade.speedU);
					PlayerPrefs.SetInt ("armor", MenuUpgrade.armorU);
					PlayerPrefs.SetInt ("char2", PlayerMenu.unlock_id_2);
					PlayerPrefs.SetInt ("char3", PlayerMenu.unlock_id_3);
					PlayerPrefs.SetInt ("char4", PlayerMenu.unlock_id_4);
					PlayerPrefs.SetInt ("char5", PlayerMenu.unlock_id_5);
					PlayerPrefs.SetInt ("char6", PlayerMenu.unlock_id_6);
					PlayerPrefs.SetInt ("char7", PlayerMenu.unlock_id_7);
					PlayerPrefs.SetInt ("char8", PlayerMenu.unlock_id_8);
					PlayerPrefs.SetInt ("char9", PlayerMenu.unlock_id_9);
					PlayerPrefs.SetInt ("char10", PlayerMenu.unlock_id_10);
					PlayerPrefs.SetInt ("char11", PlayerMenu.unlock_id_11);
					PlayerPrefs.SetInt ("char12", PlayerMenu.unlock_id_12);
					PlayerPrefs.SetInt ("char13", PlayerMenu.unlock_id_13);
					PlayerPrefs.SetInt ("char14", PlayerMenu.unlock_id_14);
					PlayerPrefs.SetInt ("char15", PlayerMenu.unlock_id_15);
					PlayerPrefs.SetInt ("char16", PlayerMenu.unlock_id_16);
					PlayerPrefs.SetInt ("char17", PlayerMenu.unlock_id_17);
					PlayerPrefs.SetInt ("char18", PlayerMenu.unlock_id_18);
					PlayerPrefs.SetInt ("char19", PlayerMenu.unlock_id_19);
					PlayerPrefs.SetInt ("char20", PlayerMenu.unlock_id_20);
					PlayerPrefs.SetInt ("char21", PlayerMenu.unlock_id_21);
					PlayerPrefs.SetInt ("char22", PlayerMenu.unlock_id_22);
					PlayerPrefs.SetInt ("char23", PlayerMenu.unlock_id_23);
					PlayerPrefs.SetInt ("char24", PlayerMenu.unlock_id_24);
					PlayerPrefs.SetInt ("char25", PlayerMenu.unlock_id_25);
					PlayerPrefs.SetInt ("char26", PlayerMenu.unlock_id_26);
					PlayerPrefs.SetInt ("char27", PlayerMenu.unlock_id_27);
					PlayerPrefs.SetInt ("char28", PlayerMenu.unlock_id_28);
					PlayerPrefs.SetInt ("char29", PlayerMenu.unlock_id_29);
					PlayerPrefs.SetInt ("char30", PlayerMenu.unlock_id_30);
					PlayerPrefs.SetInt ("char31", PlayerMenu.unlock_id_31);
					PlayerPrefs.SetInt ("char32", PlayerMenu.unlock_id_32);
					PlayerPrefs.SetInt ("char33", PlayerMenu.unlock_id_33);
					PlayerPrefs.SetInt ("char34", PlayerMenu.unlock_id_34);
					PlayerPrefs.SetInt ("char35", PlayerMenu.unlock_id_35);
					PlayerPrefs.SetInt ("char36", PlayerMenu.unlock_id_36);
					PlayerPrefs.SetInt ("char37", PlayerMenu.unlock_id_37);
					PlayerPrefs.SetInt ("char38", PlayerMenu.unlock_id_38);
					PlayerPrefs.SetInt ("char39", PlayerMenu.unlock_id_39);
					PlayerPrefs.SetInt ("char40", PlayerMenu.unlock_id_40);
					PlayerPrefs.SetInt ("char41", PlayerMenu.unlock_id_41);
					PlayerPrefs.SetInt ("char42", PlayerMenu.unlock_id_42);
					PlayerPrefs.SetInt ("char43", PlayerMenu.unlock_id_43);
					PlayerPrefs.SetInt ("char44", PlayerMenu.unlock_id_44);
					PlayerPrefs.SetInt ("char45", PlayerMenu.unlock_id_45);
					PlayerPrefs.SetInt ("char46", PlayerMenu.unlock_id_46);
					PlayerPrefs.SetInt ("char47", PlayerMenu.unlock_id_47);
					PlayerPrefs.SetInt ("char48", PlayerMenu.unlock_id_48);
					PlayerPrefs.SetInt ("char49", PlayerMenu.unlock_id_49);
					PlayerPrefs.SetInt ("char50", PlayerMenu.unlock_id_50);
					PlayerPrefs.SetInt ("char51", PlayerMenu.unlock_id_51);
					PlayerPrefs.SetInt ("char52", PlayerMenu.unlock_id_52);
					PlayerPrefs.SetInt ("char53", PlayerMenu.unlock_id_53);
					PlayerPrefs.SetInt ("char54", PlayerMenu.unlock_id_54);
					PlayerPrefs.SetInt ("char55", PlayerMenu.unlock_id_55);
					PlayerPrefs.SetInt ("char56", PlayerMenu.unlock_id_56);
					PlayerPrefs.SetInt ("char57", PlayerMenu.unlock_id_57);
					PlayerPrefs.SetInt ("char58", PlayerMenu.unlock_id_58);
					PlayerPrefs.SetInt ("char59", PlayerMenu.unlock_id_59);
					PlayerPrefs.SetInt ("char60", PlayerMenu.unlock_id_60);
					PlayerPrefs.SetInt ("char61", PlayerMenu.unlock_id_61);
					PlayerPrefs.SetInt ("char62", PlayerMenu.unlock_id_62);
					PlayerPrefs.SetInt ("char63", PlayerMenu.unlock_id_63);
					Application.LoadLevel ("LevelMenu");
				}
				
				if (GUI.Button (new Rect (300, 220, 200, 50), "主菜单")) {
					GDB.globalScore = GDB.globalScore + totalScore;
					PlayerPrefs.SetInt ("activity", GDB.activity);
					PlayerPrefs.SetFloat ("xp", GDB.xp);
					PlayerPrefs.SetInt ("lev", GDB.levXp);
					PlayerPrefs.SetInt ("score", GDB.globalScore);
					PlayerPrefs.SetInt ("ruby", GDB.redMoney);
					PlayerPrefs.SetInt ("coin", GDB.coins);
					PlayerPrefs.SetInt ("level", GDB.unlockLeavel);
					PlayerPrefs.SetInt ("saphire", GDB.blueMoney);
					PlayerPrefs.SetInt ("emerald", GDB.greenMoney);
					PlayerPrefs.SetInt ("damage", MenuUpgrade.damageU);
					PlayerPrefs.SetInt ("health", MenuUpgrade.healthU);
					PlayerPrefs.SetInt ("speed", MenuUpgrade.speedU);
					PlayerPrefs.SetInt ("armor", MenuUpgrade.armorU);
					PlayerPrefs.SetInt ("char2", PlayerMenu.unlock_id_2);
					PlayerPrefs.SetInt ("char3", PlayerMenu.unlock_id_3);
					PlayerPrefs.SetInt ("char4", PlayerMenu.unlock_id_4);
					PlayerPrefs.SetInt ("char5", PlayerMenu.unlock_id_5);
					PlayerPrefs.SetInt ("char6", PlayerMenu.unlock_id_6);
					PlayerPrefs.SetInt ("char7", PlayerMenu.unlock_id_7);
					PlayerPrefs.SetInt ("char8", PlayerMenu.unlock_id_8);
					PlayerPrefs.SetInt ("char9", PlayerMenu.unlock_id_9);
					PlayerPrefs.SetInt ("char10", PlayerMenu.unlock_id_10);
					PlayerPrefs.SetInt ("char11", PlayerMenu.unlock_id_11);
					PlayerPrefs.SetInt ("char12", PlayerMenu.unlock_id_12);
					PlayerPrefs.SetInt ("char13", PlayerMenu.unlock_id_13);
					PlayerPrefs.SetInt ("char14", PlayerMenu.unlock_id_14);
					PlayerPrefs.SetInt ("char15", PlayerMenu.unlock_id_15);
					PlayerPrefs.SetInt ("char16", PlayerMenu.unlock_id_16);
					PlayerPrefs.SetInt ("char17", PlayerMenu.unlock_id_17);
					PlayerPrefs.SetInt ("char18", PlayerMenu.unlock_id_18);
					PlayerPrefs.SetInt ("char19", PlayerMenu.unlock_id_19);
					PlayerPrefs.SetInt ("char20", PlayerMenu.unlock_id_20);
					PlayerPrefs.SetInt ("char21", PlayerMenu.unlock_id_21);
					PlayerPrefs.SetInt ("char22", PlayerMenu.unlock_id_22);
					PlayerPrefs.SetInt ("char23", PlayerMenu.unlock_id_23);
					PlayerPrefs.SetInt ("char24", PlayerMenu.unlock_id_24);
					PlayerPrefs.SetInt ("char25", PlayerMenu.unlock_id_25);
					PlayerPrefs.SetInt ("char26", PlayerMenu.unlock_id_26);
					PlayerPrefs.SetInt ("char27", PlayerMenu.unlock_id_27);
					PlayerPrefs.SetInt ("char28", PlayerMenu.unlock_id_28);
					PlayerPrefs.SetInt ("char29", PlayerMenu.unlock_id_29);
					PlayerPrefs.SetInt ("char30", PlayerMenu.unlock_id_30);
					PlayerPrefs.SetInt ("char31", PlayerMenu.unlock_id_31);
					PlayerPrefs.SetInt ("char32", PlayerMenu.unlock_id_32);
					PlayerPrefs.SetInt ("char33", PlayerMenu.unlock_id_33);
					PlayerPrefs.SetInt ("char34", PlayerMenu.unlock_id_34);
					PlayerPrefs.SetInt ("char35", PlayerMenu.unlock_id_35);
					PlayerPrefs.SetInt ("char36", PlayerMenu.unlock_id_36);
					PlayerPrefs.SetInt ("char37", PlayerMenu.unlock_id_37);
					PlayerPrefs.SetInt ("char38", PlayerMenu.unlock_id_38);
					PlayerPrefs.SetInt ("char39", PlayerMenu.unlock_id_39);
					PlayerPrefs.SetInt ("char40", PlayerMenu.unlock_id_40);
					PlayerPrefs.SetInt ("char41", PlayerMenu.unlock_id_41);
					PlayerPrefs.SetInt ("char42", PlayerMenu.unlock_id_42);
					PlayerPrefs.SetInt ("char43", PlayerMenu.unlock_id_43);
					PlayerPrefs.SetInt ("char44", PlayerMenu.unlock_id_44);
					PlayerPrefs.SetInt ("char45", PlayerMenu.unlock_id_45);
					PlayerPrefs.SetInt ("char46", PlayerMenu.unlock_id_46);
					PlayerPrefs.SetInt ("char47", PlayerMenu.unlock_id_47);
					PlayerPrefs.SetInt ("char48", PlayerMenu.unlock_id_48);
					PlayerPrefs.SetInt ("char49", PlayerMenu.unlock_id_49);
					PlayerPrefs.SetInt ("char50", PlayerMenu.unlock_id_50);
					PlayerPrefs.SetInt ("char51", PlayerMenu.unlock_id_51);
					PlayerPrefs.SetInt ("char52", PlayerMenu.unlock_id_52);
					PlayerPrefs.SetInt ("char53", PlayerMenu.unlock_id_53);
					PlayerPrefs.SetInt ("char54", PlayerMenu.unlock_id_54);
					PlayerPrefs.SetInt ("char55", PlayerMenu.unlock_id_55);
					PlayerPrefs.SetInt ("char56", PlayerMenu.unlock_id_56);
					PlayerPrefs.SetInt ("char57", PlayerMenu.unlock_id_57);
					PlayerPrefs.SetInt ("char58", PlayerMenu.unlock_id_58);
					PlayerPrefs.SetInt ("char59", PlayerMenu.unlock_id_59);
					PlayerPrefs.SetInt ("char60", PlayerMenu.unlock_id_60);
					PlayerPrefs.SetInt ("char61", PlayerMenu.unlock_id_61);
					PlayerPrefs.SetInt ("char62", PlayerMenu.unlock_id_62);
					PlayerPrefs.SetInt ("char63", PlayerMenu.unlock_id_63);
					Application.LoadLevel ("Menu");
				}
				
				if (GUI.Button (new Rect (300, 160, 200, 50), "一个菜单的表情")) {
					GDB.globalScore = GDB.globalScore + totalScore;
					PlayerPrefs.SetInt ("activity", GDB.activity);
					PlayerPrefs.SetFloat ("xp", GDB.xp);
					PlayerPrefs.SetInt ("lev", GDB.levXp);
					PlayerPrefs.SetInt ("score", GDB.globalScore);
					PlayerPrefs.SetInt ("ruby", GDB.redMoney);
					PlayerPrefs.SetInt ("coin", GDB.coins);
					PlayerPrefs.SetInt ("level", GDB.unlockLeavel);
					PlayerPrefs.SetInt ("saphire", GDB.blueMoney);
					PlayerPrefs.SetInt ("emerald", GDB.greenMoney);
					PlayerPrefs.SetInt ("damage", MenuUpgrade.damageU);
					PlayerPrefs.SetInt ("health", MenuUpgrade.healthU);
					PlayerPrefs.SetInt ("speed", MenuUpgrade.speedU);
					PlayerPrefs.SetInt ("armor", MenuUpgrade.armorU);
					PlayerPrefs.SetInt ("char2", PlayerMenu.unlock_id_2);
					PlayerPrefs.SetInt ("char3", PlayerMenu.unlock_id_3);
					PlayerPrefs.SetInt ("char4", PlayerMenu.unlock_id_4);
					PlayerPrefs.SetInt ("char5", PlayerMenu.unlock_id_5);
					PlayerPrefs.SetInt ("char6", PlayerMenu.unlock_id_6);
					PlayerPrefs.SetInt ("char7", PlayerMenu.unlock_id_7);
					PlayerPrefs.SetInt ("char8", PlayerMenu.unlock_id_8);
					PlayerPrefs.SetInt ("char9", PlayerMenu.unlock_id_9);
					PlayerPrefs.SetInt ("char10", PlayerMenu.unlock_id_10);
					PlayerPrefs.SetInt ("char11", PlayerMenu.unlock_id_11);
					PlayerPrefs.SetInt ("char12", PlayerMenu.unlock_id_12);
					PlayerPrefs.SetInt ("char13", PlayerMenu.unlock_id_13);
					PlayerPrefs.SetInt ("char14", PlayerMenu.unlock_id_14);
					PlayerPrefs.SetInt ("char15", PlayerMenu.unlock_id_15);
					PlayerPrefs.SetInt ("char16", PlayerMenu.unlock_id_16);
					PlayerPrefs.SetInt ("char17", PlayerMenu.unlock_id_17);
					PlayerPrefs.SetInt ("char18", PlayerMenu.unlock_id_18);
					PlayerPrefs.SetInt ("char19", PlayerMenu.unlock_id_19);
					PlayerPrefs.SetInt ("char20", PlayerMenu.unlock_id_20);
					PlayerPrefs.SetInt ("char21", PlayerMenu.unlock_id_21);
					PlayerPrefs.SetInt ("char22", PlayerMenu.unlock_id_22);
					PlayerPrefs.SetInt ("char23", PlayerMenu.unlock_id_23);
					PlayerPrefs.SetInt ("char24", PlayerMenu.unlock_id_24);
					PlayerPrefs.SetInt ("char25", PlayerMenu.unlock_id_25);
					PlayerPrefs.SetInt ("char26", PlayerMenu.unlock_id_26);
					PlayerPrefs.SetInt ("char27", PlayerMenu.unlock_id_27);
					PlayerPrefs.SetInt ("char28", PlayerMenu.unlock_id_28);
					PlayerPrefs.SetInt ("char29", PlayerMenu.unlock_id_29);
					PlayerPrefs.SetInt ("char30", PlayerMenu.unlock_id_30);
					PlayerPrefs.SetInt ("char31", PlayerMenu.unlock_id_31);
					PlayerPrefs.SetInt ("char32", PlayerMenu.unlock_id_32);
					PlayerPrefs.SetInt ("char33", PlayerMenu.unlock_id_33);
					PlayerPrefs.SetInt ("char34", PlayerMenu.unlock_id_34);
					PlayerPrefs.SetInt ("char35", PlayerMenu.unlock_id_35);
					PlayerPrefs.SetInt ("char36", PlayerMenu.unlock_id_36);
					PlayerPrefs.SetInt ("char37", PlayerMenu.unlock_id_37);
					PlayerPrefs.SetInt ("char38", PlayerMenu.unlock_id_38);
					PlayerPrefs.SetInt ("char39", PlayerMenu.unlock_id_39);
					PlayerPrefs.SetInt ("char40", PlayerMenu.unlock_id_40);
					PlayerPrefs.SetInt ("char41", PlayerMenu.unlock_id_41);
					PlayerPrefs.SetInt ("char42", PlayerMenu.unlock_id_42);
					PlayerPrefs.SetInt ("char43", PlayerMenu.unlock_id_43);
					PlayerPrefs.SetInt ("char44", PlayerMenu.unlock_id_44);
					PlayerPrefs.SetInt ("char45", PlayerMenu.unlock_id_45);
					PlayerPrefs.SetInt ("char46", PlayerMenu.unlock_id_46);
					PlayerPrefs.SetInt ("char47", PlayerMenu.unlock_id_47);
					PlayerPrefs.SetInt ("char48", PlayerMenu.unlock_id_48);
					PlayerPrefs.SetInt ("char49", PlayerMenu.unlock_id_49);
					PlayerPrefs.SetInt ("char50", PlayerMenu.unlock_id_50);
					PlayerPrefs.SetInt ("char51", PlayerMenu.unlock_id_51);
					PlayerPrefs.SetInt ("char52", PlayerMenu.unlock_id_52);
					PlayerPrefs.SetInt ("char53", PlayerMenu.unlock_id_53);
					PlayerPrefs.SetInt ("char54", PlayerMenu.unlock_id_54);
					PlayerPrefs.SetInt ("char55", PlayerMenu.unlock_id_55);
					PlayerPrefs.SetInt ("char56", PlayerMenu.unlock_id_56);
					PlayerPrefs.SetInt ("char57", PlayerMenu.unlock_id_57);
					PlayerPrefs.SetInt ("char58", PlayerMenu.unlock_id_58);
					PlayerPrefs.SetInt ("char59", PlayerMenu.unlock_id_59);
					PlayerPrefs.SetInt ("char60", PlayerMenu.unlock_id_60);
					PlayerPrefs.SetInt ("char61", PlayerMenu.unlock_id_61);
					PlayerPrefs.SetInt ("char62", PlayerMenu.unlock_id_62);
					PlayerPrefs.SetInt ("char63", PlayerMenu.unlock_id_63);
					Application.LoadLevel ("PlayerMenu");
				}
			}
		}
	}
}
